name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - name: Setup node@18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i --ignore-scripts

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          publish: pnpm changeset:release
          commit: 'chore(changeset): bump version'
          title: 'chore(changeset): bump version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
